// Dumps the locally-seeded SQLite DB (./data/ielts.sqlite) to D1-compatible
// SQL INSERT statements at ./data/seed.sql.
//
// Run the seed first (creates data/ielts.sqlite), then this:
//
//   node --experimental-strip-types scripts/seed.ts
//   node --experimental-strip-types scripts/dump-d1-sql.ts
//
// Then push to D1:
//
//   npx wrangler d1 execute ielts-db --remote --file=./data/seed.sql
//
// We intentionally DO NOT dump `attempts` / `answers` — those are runtime data.

import Database from 'better-sqlite3'
import { writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const dbPath = resolve(process.cwd(), './data/ielts.sqlite')
if (!existsSync(dbPath)) {
  console.error(`[dump] missing ${dbPath} — run \`npm run seed:local-sqlite\` first.`)
  process.exit(1)
}

const db = new Database(dbPath, { readonly: true })
const tables = ['users', 'tests', 'sections', 'questions']

const out: string[] = []
out.push('-- Auto-generated by scripts/dump-d1-sql.ts — do not edit by hand.')
out.push('-- Source: data/ielts.sqlite   Target: Cloudflare D1 (ielts-db)')
out.push('')
out.push('-- Clear any existing rows so this script is idempotent.')
out.push('DELETE FROM answers;')
out.push('DELETE FROM attempts;')
out.push('DELETE FROM questions;')
out.push('DELETE FROM sections;')
out.push('DELETE FROM tests;')
out.push('DELETE FROM users;')
out.push('')

let total = 0
for (const t of tables) {
  const rows = db.prepare(`SELECT * FROM ${t}`).all() as Record<string, any>[]
  if (!rows.length) {
    out.push(`-- ${t}: (empty)`)
    out.push('')
    continue
  }
  const cols = Object.keys(rows[0])
  out.push(`-- ${t}: ${rows.length} row(s)`)
  for (const row of rows) {
    const vals = cols.map((c) => toSqlLiteral(row[c]))
    out.push(`INSERT INTO ${t} (${cols.join(', ')}) VALUES (${vals.join(', ')});`)
    total++
  }
  out.push('')
}

function toSqlLiteral(v: any): string {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL'
  if (typeof v === 'boolean') return v ? '1' : '0'
  if (v instanceof Uint8Array || (v && typeof v === 'object' && 'buffer' in v && 'byteLength' in v)) {
    // BLOB → x'...'
    const buf = Buffer.from(v as Uint8Array)
    return `x'${buf.toString('hex')}'`
  }
  const s = String(v)
  return `'${s.replace(/'/g, "''")}'`
}

const outPath = resolve(process.cwd(), './data/seed.sql')
writeFileSync(outPath, out.join('\n'))
db.close()
console.log(`[dump] wrote ${outPath} — ${total} INSERT statement(s).`)
console.log('[dump] next:  npx wrangler d1 execute ielts-db --remote --file=./data/seed.sql')
